services:
  backend:
    build: .
    container_name: mini-vault-backend
    ports:
      - "8000:8000"
    environment:
      - DB_FILE=/app/data/mini_vault.db
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./mini-vault-frontend
    container_name: mini-vault-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend #making sure the backend runs first